name: e2e

on:
  # schedule:
  #   - cron: '17 4 * * *'
  workflow_call: {}
  workflow_dispatch:

jobs:

  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@main

    - name: Build & start containers
      run: cd tests/e2e && docker compose up --detach --build

    - name: Run tests
      run: cd tests/e2e && docker compose exec drupal venom run
      env:
        # Allow proper output.
        IS_TTY: true
