name: e2e

on:
  # schedule:
  #   - cron: '17 4 * * *'
  workflow_call: {}
  workflow_dispatch:

jobs:

  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@main

    - name: Build & start containers
      run: docker compose up --detach --build

    - name: Run tests
      run: |
        set -ex
        docker compose exec drupal tree
        docker compose exec drupal ls -l /app
        docker compose exec drupal venom run
      # env:
      #   # Allow proper output.
      #   IS_TTY: true

    - name: Upload venom log
      uses: actions/upload-artifact@main
      with:
        name: venom-log
        path: tests/e2e/suites/venom.log
      if: always()
