name: Go

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Vet
      run: go vet ./...

    - name: Build
      run: go build -ldflags="-s -w" -o build/shipshape . && ls -lh build/shipshape

    - name: Test
      run: go test -v ./... -coverprofile=build/coverage.out

    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: build/coverage.out

    - name: Upload test coverage
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
      if: github.ref_name == 'main'

    - name: Fetch all tags
      run: git fetch --force --tags
      if: startsWith(github.ref_name, 'v')

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref_name, 'v')
